---
plugin: aws_ec2
aws_profile: default
regions:
  - us-east-1
filters:
  tag:Name:
    - web
  instance-state-name : running
keyed_groups:
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: aws_instance_type
  - key: placement.region
    prefix: aws_region
  