# Provision Server
- hosts: localhost
  vars_files:
  - secret.yml
  roles:
  - role: server-provision
    # ec2key: "ec2key"
    count: 1
    tag_name: "webserver"
    accesskey: "{{ akey }}"
    secretkey: "{{ skey }}"
